### ISSUE TITLE
Horizontal View

### ISSUE THREAD

**Issue by isheta** [joeldbirch/superclick#2]
Hey,
I'm using Superclick, first of all ,awesome plugin, really saves time.
Question : i have couple of menus in my site, i want part of them to be horizontal in first click and part of them to be vertical in first click..any way to do so?

**Comment by isheta** [comment]
it would be awesome to get an answer, thanks.

**Comment by joeldbirch** [comment]
While I'm not certain I completely follow what you are trying to achieve, I think the answer is: yes, just add the class `sf-vertical` to the menu you want to style vertically (in addition to the usual `sf-menu` class), and make sure you include the extra superfish-vertical.css file. There is [a page about this in the Superfish documentation](http://users.tpg.com.au/j_birch/plugins/superfish/examples/vertical/). Hope this helps.
