### ISSUE TITLE
window detection

### ISSUE THREAD

**Issue by sede1900** [joeldbirch/superclick#6]
is it possible to add window dectection to your superclick plugin ? I use superfish with some drupal sites and I have this behaviour with superfish 
you can see it at https://www.smals.be/fr/news/range for example

 you can see a superfish menu and when we reach the side of the window 
the menu stays always visible 

I know that supposition plugin was used but I don't see it in your archive superclick

do you have an another solution ? My new site has 4 menus and the menu is 100% of the page. with 3 or 4 levels ...

thank you

**Comment by joeldbirch** [comment]
I usually just position the menus with CSS to suit the space at various media query breakpoints. For example, if the right-most submenu is too close to the edge, I'll align that one right, etc. Not exactly what you are looking for, I know.

The [latest version of the Supposition plugin can be found here](https://gist.github.com/joeldbirch/5371649) but, as hinted by it living in a Gist, it's not supported. See if it does the job for you, though.
